Khwahish
MayankRawat06/ERRSFastenal pull request #6
Opened 2024-01-19 05:47 UTC by khwahish2oo2

2024-01-19 09:40 UTC, MayankRawat06 requested changes

2024-01-19 09:40 UTC, MayankRawat06 commented on app.py
> +def redeem_points():
make it just redeem

2024-01-19 09:40 UTC, MayankRawat06 commented on app.py
> +@app.route("/register", methods=['GET', 'POST'])
remove register section

2024-01-19 09:40 UTC, MayankRawat06 commented on static/styles.css
> +body {
totlly different css, do something to integrate

2024-01-19 09:40 UTC, MayankRawat06 commented on templates/layout.html
> +                <a class="nav-link" href="/redeem_points">Redeem</a>
just redeem

2024-01-19 09:40 UTC, MayankRawat06 commented on templates/layout.html
> +                <a class="nav-link" href="/post_idea">post</a>
why we're adding this?

2024-01-20 10:05 UTC, vijay-72 commented on templates/layout.html
> +                <a class="nav-link" href="/Profile">Profile</a>
/profile would be more standard

2024-01-20 10:32 UTC, merged